from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.dba_profile_vo_type import DBAProfileVOType
from ..types import UNSET, Unset

T = TypeVar("T", bound="DBAProfileVO")


@_attrs_define
class DBAProfileVO:
    """Content

    Attributes:
        type_ (DBAProfileVOType): DBA bandwidth allocation methods.Type should be a value as follows: FIX, ASSURE, MAX,
            ASSURE_MAX, and FIX_ASSURE_MAX. The default value is FIX.
        dba_id (int | Unset): DBA ID should be within the range of 1 to 512.
        name (str | Unset): The name of the DBA profile should contain 1 to 32 characters including digits, upper and
            lower letters, and the following six characters: -@_:/. .
        is_system_profile (bool | Unset): IsSystemProfile should be null, because it's generated by device.
        is_in_use (str | Unset): Whether the DBA profile is in use.DBA Profile cannot be deleted if it has already been
            used. A value of true indicates that it has been used, while false indicates that it has not been used. If this
            field is not provided, the default value is false.
        fix (int | Unset): The value for fixed bandwidth is only required when the Type is set to FIX or FIX_ASSURE_MAX.
            Fix should be within the range of 128 to 720000, with the unit in kbit/s.
        assure (int | Unset): The value for guaranteed bandwidth is required when the Type is set to ASSURE, ASSURE_MAX,
            or FIX_ASSURE_MAX. Assure should be within the range of 128 to 1200000, with the unit in kbit/s.
        max_ (int | Unset): The value for maximum bandwidth is required when the Type is set to MAX, ASSURE_MAX, or
            FIX_ASSURE_MAX. Max should be within the range of 128 to 1244160, with the unit in kbit/s.
        tcont_num (int | Unset): The number of T-conts using this DBA template is not configurable and will be returned
            upon inquiry.
    """

    type_: DBAProfileVOType
    dba_id: int | Unset = UNSET
    name: str | Unset = UNSET
    is_system_profile: bool | Unset = UNSET
    is_in_use: str | Unset = UNSET
    fix: int | Unset = UNSET
    assure: int | Unset = UNSET
    max_: int | Unset = UNSET
    tcont_num: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        type_ = self.type_.value

        dba_id = self.dba_id

        name = self.name

        is_system_profile = self.is_system_profile

        is_in_use = self.is_in_use

        fix = self.fix

        assure = self.assure

        max_ = self.max_

        tcont_num = self.tcont_num

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "type": type_,
            }
        )
        if dba_id is not UNSET:
            field_dict["dbaId"] = dba_id
        if name is not UNSET:
            field_dict["name"] = name
        if is_system_profile is not UNSET:
            field_dict["isSystemProfile"] = is_system_profile
        if is_in_use is not UNSET:
            field_dict["isInUse"] = is_in_use
        if fix is not UNSET:
            field_dict["fix"] = fix
        if assure is not UNSET:
            field_dict["assure"] = assure
        if max_ is not UNSET:
            field_dict["max"] = max_
        if tcont_num is not UNSET:
            field_dict["tcontNum"] = tcont_num

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        type_ = DBAProfileVOType(d.pop("type"))

        dba_id = d.pop("dbaId", UNSET)

        name = d.pop("name", UNSET)

        is_system_profile = d.pop("isSystemProfile", UNSET)

        is_in_use = d.pop("isInUse", UNSET)

        fix = d.pop("fix", UNSET)

        assure = d.pop("assure", UNSET)

        max_ = d.pop("max", UNSET)

        tcont_num = d.pop("tcontNum", UNSET)

        dba_profile_vo = cls(
            type_=type_,
            dba_id=dba_id,
            name=name,
            is_system_profile=is_system_profile,
            is_in_use=is_in_use,
            fix=fix,
            assure=assure,
            max_=max_,
            tcont_num=tcont_num,
        )

        dba_profile_vo.additional_properties = d
        return dba_profile_vo

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
