from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.line_profile_modify_dto_mapping_mode import (
    LineProfileModifyDTOMappingMode,
)
from ..models.line_profile_modify_dto_omcc_encrypt import (
    LineProfileModifyDTOOmccEncrypt,
)
from ..models.line_profile_modify_dto_upstream_fec import (
    LineProfileModifyDTOUpstreamFEC,
)
from ..types import UNSET, Unset

T = TypeVar("T", bound="LineProfileModifyDTO")


@_attrs_define
class LineProfileModifyDTO:
    """
    Attributes:
        line_profile_id (int): LineProfileId should be within the range of 1 to 512
        name (str | Unset): The name of the Line template, an optional configuration. If not configured by the user, it
            will be automatically generated by the device. Name should contain 1 to 32 characters including digits, upper
            and lower letters, and the following six characters: -@_:/. . It can be left empty; if empty, it will be
            assigned automatically by the device.
        upstream_fec (LineProfileModifyDTOUpstreamFEC | Unset): Enable/Disable Upstream FEC feature. UpStreamFEC should
            be a value as follows: DISABLE;ENABLE. Default value: DISABLE.
        mapping_mode (LineProfileModifyDTOMappingMode | Unset): Mapping method for the ONT. MappingMode should be a
            value as follows: VLAN, PRIORITY, VLAN_PRIORITY, PORT, PORT_VLAN, PORT_PRIORITY, PORT_VLAN_PRIORITY. Default
            value: VLAN.
        omcc_encrypt (LineProfileModifyDTOOmccEncrypt | Unset): Whether to enable OMCC encryption feature: when OMCC
            encryption is enabled, OMCI messages will be encrypted; otherwise, they will not be encrypted. OmccEncrypt
            should be a value as follows: ENABLE;DISABLE. Default value: DISABLE.
    """

    line_profile_id: int
    name: str | Unset = UNSET
    upstream_fec: LineProfileModifyDTOUpstreamFEC | Unset = UNSET
    mapping_mode: LineProfileModifyDTOMappingMode | Unset = UNSET
    omcc_encrypt: LineProfileModifyDTOOmccEncrypt | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        line_profile_id = self.line_profile_id

        name = self.name

        upstream_fec: str | Unset = UNSET
        if not isinstance(self.upstream_fec, Unset):
            upstream_fec = self.upstream_fec.value

        mapping_mode: str | Unset = UNSET
        if not isinstance(self.mapping_mode, Unset):
            mapping_mode = self.mapping_mode.value

        omcc_encrypt: str | Unset = UNSET
        if not isinstance(self.omcc_encrypt, Unset):
            omcc_encrypt = self.omcc_encrypt.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "lineProfileId": line_profile_id,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if upstream_fec is not UNSET:
            field_dict["upstreamFEC"] = upstream_fec
        if mapping_mode is not UNSET:
            field_dict["mappingMode"] = mapping_mode
        if omcc_encrypt is not UNSET:
            field_dict["omccEncrypt"] = omcc_encrypt

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        line_profile_id = d.pop("lineProfileId")

        name = d.pop("name", UNSET)

        _upstream_fec = d.pop("upstreamFEC", UNSET)
        upstream_fec: LineProfileModifyDTOUpstreamFEC | Unset
        if isinstance(_upstream_fec, Unset):
            upstream_fec = UNSET
        else:
            upstream_fec = LineProfileModifyDTOUpstreamFEC(_upstream_fec)

        _mapping_mode = d.pop("mappingMode", UNSET)
        mapping_mode: LineProfileModifyDTOMappingMode | Unset
        if isinstance(_mapping_mode, Unset):
            mapping_mode = UNSET
        else:
            mapping_mode = LineProfileModifyDTOMappingMode(_mapping_mode)

        _omcc_encrypt = d.pop("omccEncrypt", UNSET)
        omcc_encrypt: LineProfileModifyDTOOmccEncrypt | Unset
        if isinstance(_omcc_encrypt, Unset):
            omcc_encrypt = UNSET
        else:
            omcc_encrypt = LineProfileModifyDTOOmccEncrypt(_omcc_encrypt)

        line_profile_modify_dto = cls(
            line_profile_id=line_profile_id,
            name=name,
            upstream_fec=upstream_fec,
            mapping_mode=mapping_mode,
            omcc_encrypt=omcc_encrypt,
        )

        line_profile_modify_dto.additional_properties = d
        return line_profile_modify_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
