from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.line_profile_dto_mapping_mode import LineProfileDTOMappingMode
from ..models.line_profile_dto_omcc_encrypt import LineProfileDTOOmccEncrypt
from ..models.line_profile_dto_upstream_fec import LineProfileDTOUpstreamFEC
from ..types import UNSET, Unset

T = TypeVar("T", bound="LineProfileDTO")


@_attrs_define
class LineProfileDTO:
    """
    Attributes:
        line_profile_id (int): ID of line profile should be within the range of 1 to 512 and should not be null
        upstream_fec (LineProfileDTOUpstreamFEC): Enable/Disable Upstream FEC feature. UpstreamFEC should be a value as
            follows: DISABLE;ENABLE.
        mapping_mode (LineProfileDTOMappingMode): Mapping method for the ONT. MappingMode should be a value as follows:
            VLAN, PRIORITY, VLAN_PRIORITY, PORT, PORT_VLAN, PORT_PRIORITY, PORT_VLAN_PRIORITY. Default value: VLAN.
        name (str | Unset): The name of the Line template, an optional configuration. If not configured by the user, it
            will be automatically generated by the device. Name should contain 1 to 32 characters including digits, upper
            and lower letters, and the following six characters: -@_:/. . It can be left empty; if empty, it will be
            assigned automatically by the device.
        is_system_profile (bool | Unset): IsSystemProfile should be null, because it's generated by device.
        is_in_use (bool | Unset): Whether the Line Profile is in use: if it is in use, deletion is not allowed. True
            indicates it is in use, while false indicates it is not in use. This field should not be provided
        omcc_encrypt (LineProfileDTOOmccEncrypt | Unset): Whether to enable OMCC encryption feature: when OMCC
            encryption is enabled, OMCI messages will be encrypted; otherwise, they will not be encrypted. OmccEncrypt
            should be a value as follows: ENABLE;DISABLE. Default value: ENABLE.
        tcont_num (int | Unset): The number of T-conts created under this Line template is non-configurable.
        gem_port_num (int | Unset): The number of gem ports created under this Line template is non-configurable.
    """

    line_profile_id: int
    upstream_fec: LineProfileDTOUpstreamFEC
    mapping_mode: LineProfileDTOMappingMode
    name: str | Unset = UNSET
    is_system_profile: bool | Unset = UNSET
    is_in_use: bool | Unset = UNSET
    omcc_encrypt: LineProfileDTOOmccEncrypt | Unset = UNSET
    tcont_num: int | Unset = UNSET
    gem_port_num: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        line_profile_id = self.line_profile_id

        upstream_fec = self.upstream_fec.value

        mapping_mode = self.mapping_mode.value

        name = self.name

        is_system_profile = self.is_system_profile

        is_in_use = self.is_in_use

        omcc_encrypt: str | Unset = UNSET
        if not isinstance(self.omcc_encrypt, Unset):
            omcc_encrypt = self.omcc_encrypt.value

        tcont_num = self.tcont_num

        gem_port_num = self.gem_port_num

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "lineProfileId": line_profile_id,
                "upstreamFEC": upstream_fec,
                "mappingMode": mapping_mode,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if is_system_profile is not UNSET:
            field_dict["isSystemProfile"] = is_system_profile
        if is_in_use is not UNSET:
            field_dict["isInUse"] = is_in_use
        if omcc_encrypt is not UNSET:
            field_dict["omccEncrypt"] = omcc_encrypt
        if tcont_num is not UNSET:
            field_dict["tcontNum"] = tcont_num
        if gem_port_num is not UNSET:
            field_dict["gemPortNum"] = gem_port_num

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        line_profile_id = d.pop("lineProfileId")

        upstream_fec = LineProfileDTOUpstreamFEC(d.pop("upstreamFEC"))

        mapping_mode = LineProfileDTOMappingMode(d.pop("mappingMode"))

        name = d.pop("name", UNSET)

        is_system_profile = d.pop("isSystemProfile", UNSET)

        is_in_use = d.pop("isInUse", UNSET)

        _omcc_encrypt = d.pop("omccEncrypt", UNSET)
        omcc_encrypt: LineProfileDTOOmccEncrypt | Unset
        if isinstance(_omcc_encrypt, Unset):
            omcc_encrypt = UNSET
        else:
            omcc_encrypt = LineProfileDTOOmccEncrypt(_omcc_encrypt)

        tcont_num = d.pop("tcontNum", UNSET)

        gem_port_num = d.pop("gemPortNum", UNSET)

        line_profile_dto = cls(
            line_profile_id=line_profile_id,
            upstream_fec=upstream_fec,
            mapping_mode=mapping_mode,
            name=name,
            is_system_profile=is_system_profile,
            is_in_use=is_in_use,
            omcc_encrypt=omcc_encrypt,
            tcont_num=tcont_num,
            gem_port_num=gem_port_num,
        )

        line_profile_dto.additional_properties = d
        return line_profile_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
