from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..types import UNSET, Unset

T = TypeVar("T", bound="ServicePortProfileModifyDTO")


@_attrs_define
class ServicePortProfileModifyDTO:
    """
    Attributes:
        service_port_profile_id (str): Service port template ID. The servicePortProfileId should be within the range of
            1 to 512, E.g.,1. It can be obtained from "Get service port profile list" interface.
        service_port_profile_name (str | Unset): Name of the service port template. No user configuration is
            automatically generated by the device. The name should contain 1 to 32 characters, including upper and lower
            letters, numbers, and symbols (-@_:/.).
    """

    service_port_profile_id: str
    service_port_profile_name: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        service_port_profile_id = self.service_port_profile_id

        service_port_profile_name = self.service_port_profile_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "servicePortProfileId": service_port_profile_id,
            }
        )
        if service_port_profile_name is not UNSET:
            field_dict["servicePortProfileName"] = service_port_profile_name

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        service_port_profile_id = d.pop("servicePortProfileId")

        service_port_profile_name = d.pop("servicePortProfileName", UNSET)

        service_port_profile_modify_dto = cls(
            service_port_profile_id=service_port_profile_id,
            service_port_profile_name=service_port_profile_name,
        )

        service_port_profile_modify_dto.additional_properties = d
        return service_port_profile_modify_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
