from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..types import UNSET, Unset

T = TypeVar("T", bound="ServicePortProfileDTO")


@_attrs_define
class ServicePortProfileDTO:
    """Content

    Attributes:
        service_port_profile_id (str): Service port template ID. The servicePortProfileId should be within the range of
            1 to 512. E.g.,1.
        service_port_profile_name (str): Name of the service port template. No user configuration is automatically
            generated by the device. The name should contain 1 to 32 characters, including upper and lower letters, numbers,
            and symbols (-@_:/.).
        in_use (str): Whether service port profile has been used.
        entries_number (int | Unset): Service port number. The entriesNumber should be within the range of 0 to 127.
    """

    service_port_profile_id: str
    service_port_profile_name: str
    in_use: str
    entries_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        service_port_profile_id = self.service_port_profile_id

        service_port_profile_name = self.service_port_profile_name

        in_use = self.in_use

        entries_number = self.entries_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "servicePortProfileId": service_port_profile_id,
                "servicePortProfileName": service_port_profile_name,
                "inUse": in_use,
            }
        )
        if entries_number is not UNSET:
            field_dict["entriesNumber"] = entries_number

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        service_port_profile_id = d.pop("servicePortProfileId")

        service_port_profile_name = d.pop("servicePortProfileName")

        in_use = d.pop("inUse")

        entries_number = d.pop("entriesNumber", UNSET)

        service_port_profile_dto = cls(
            service_port_profile_id=service_port_profile_id,
            service_port_profile_name=service_port_profile_name,
            in_use=in_use,
            entries_number=entries_number,
        )

        service_port_profile_dto.additional_properties = d
        return service_port_profile_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
