from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.service_profile_dto_mac_learning import ServiceProfileDTOMacLearning
from ..models.service_profile_dto_multicast_forward import (
    ServiceProfileDTOMulticastForward,
)
from ..models.service_profile_dto_multicast_mode import ServiceProfileDTOMulticastMode
from ..models.service_profile_dto_native_vlan import ServiceProfileDTONativeVlan
from ..models.service_profile_dto_tagged_type import ServiceProfileDTOTaggedType
from ..types import UNSET, Unset

T = TypeVar("T", bound="ServiceProfileDTO")


@_attrs_define
class ServiceProfileDTO:
    """
    Attributes:
        service_id (int): Service profile ID should be within the range of 1 to 512
        eth_num (int): Number of eth port.EthNum should be within the range of -1 to 24.-1 indicates that the number of
            ports is adaptive. The default value is -1.
        pots_num (int): Number of ONU pots.PotsNum should be within the range of -1 to 8.-1 indicates that the number of
            ports is adaptive. The default value is -1.
        mac_learning (ServiceProfileDTOMacLearning): Enable/disable ONT MAC address learning function. MacLearning
            should be a value as follows:DISABLE,ENABLE
        native_vlan (ServiceProfileDTONativeVlan): The ONT's concern for Native VLAN .NativeVlan should be a value as
            follows:UNCONCERN,CONCERN
        multicast_mode (ServiceProfileDTOMulticastMode): Set the multicast mode of the ONT. MulticastMode should be a
            value as follows:UNCONCERN,IGMP_SNOOPING,OLT_CONTROL
        multicast_forward (ServiceProfileDTOMulticastForward): Set the multicast packet forwarding mode of the ONT.
            NativeVlan should be a value as follows:UNCONCERN,TAGGED,UNTAGGED
        is_in_use (bool | Unset): Whether the service profile is in use
        name (str | Unset): Name of the service profile. No user configuration is automatically generated by the device.
            The name should contain 1 to 32 characters, including upper and lower letters, numbers, and symbols (-@_:/.).
        max_adaptive_eth_num (int | Unset): Set the maximum number of automatically recognized ETH ports.When ethNum is
            set to -1, a prompt will appear.MaxAdaptiveEthNum should be within the range of 0 to 24
        max_adaptive_pots_num (int | Unset): Set the maximum number of automatically recognized potsWhen potsNum is set
            to -1, a prompt will appear.MaxAdaptivePotsNum should be within the range of 0 to 4
        tagged_type (ServiceProfileDTOTaggedType | Unset): TaggedType should be a value as
            follows:TRANSPARENT,TRANSLATION
        tagged_vlan_id (int | Unset): TaggedVlanId should be within the range of 1–4094
        onu_bind_num (int | Unset): The number of ONU/ONT instances that use this Service template.
    """

    service_id: int
    eth_num: int
    pots_num: int
    mac_learning: ServiceProfileDTOMacLearning
    native_vlan: ServiceProfileDTONativeVlan
    multicast_mode: ServiceProfileDTOMulticastMode
    multicast_forward: ServiceProfileDTOMulticastForward
    is_in_use: bool | Unset = UNSET
    name: str | Unset = UNSET
    max_adaptive_eth_num: int | Unset = UNSET
    max_adaptive_pots_num: int | Unset = UNSET
    tagged_type: ServiceProfileDTOTaggedType | Unset = UNSET
    tagged_vlan_id: int | Unset = UNSET
    onu_bind_num: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        service_id = self.service_id

        eth_num = self.eth_num

        pots_num = self.pots_num

        mac_learning = self.mac_learning.value

        native_vlan = self.native_vlan.value

        multicast_mode = self.multicast_mode.value

        multicast_forward = self.multicast_forward.value

        is_in_use = self.is_in_use

        name = self.name

        max_adaptive_eth_num = self.max_adaptive_eth_num

        max_adaptive_pots_num = self.max_adaptive_pots_num

        tagged_type: str | Unset = UNSET
        if not isinstance(self.tagged_type, Unset):
            tagged_type = self.tagged_type.value

        tagged_vlan_id = self.tagged_vlan_id

        onu_bind_num = self.onu_bind_num

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "serviceId": service_id,
                "ethNum": eth_num,
                "potsNum": pots_num,
                "macLearning": mac_learning,
                "nativeVlan": native_vlan,
                "multicastMode": multicast_mode,
                "multicastForward": multicast_forward,
            }
        )
        if is_in_use is not UNSET:
            field_dict["isInUse"] = is_in_use
        if name is not UNSET:
            field_dict["name"] = name
        if max_adaptive_eth_num is not UNSET:
            field_dict["maxAdaptiveEthNum"] = max_adaptive_eth_num
        if max_adaptive_pots_num is not UNSET:
            field_dict["maxAdaptivePotsNum"] = max_adaptive_pots_num
        if tagged_type is not UNSET:
            field_dict["taggedType"] = tagged_type
        if tagged_vlan_id is not UNSET:
            field_dict["taggedVlanId"] = tagged_vlan_id
        if onu_bind_num is not UNSET:
            field_dict["onuBindNum"] = onu_bind_num

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        service_id = d.pop("serviceId")

        eth_num = d.pop("ethNum")

        pots_num = d.pop("potsNum")

        mac_learning = ServiceProfileDTOMacLearning(d.pop("macLearning"))

        native_vlan = ServiceProfileDTONativeVlan(d.pop("nativeVlan"))

        multicast_mode = ServiceProfileDTOMulticastMode(d.pop("multicastMode"))

        multicast_forward = ServiceProfileDTOMulticastForward(d.pop("multicastForward"))

        is_in_use = d.pop("isInUse", UNSET)

        name = d.pop("name", UNSET)

        max_adaptive_eth_num = d.pop("maxAdaptiveEthNum", UNSET)

        max_adaptive_pots_num = d.pop("maxAdaptivePotsNum", UNSET)

        _tagged_type = d.pop("taggedType", UNSET)
        tagged_type: ServiceProfileDTOTaggedType | Unset
        if isinstance(_tagged_type, Unset):
            tagged_type = UNSET
        else:
            tagged_type = ServiceProfileDTOTaggedType(_tagged_type)

        tagged_vlan_id = d.pop("taggedVlanId", UNSET)

        onu_bind_num = d.pop("onuBindNum", UNSET)

        service_profile_dto = cls(
            service_id=service_id,
            eth_num=eth_num,
            pots_num=pots_num,
            mac_learning=mac_learning,
            native_vlan=native_vlan,
            multicast_mode=multicast_mode,
            multicast_forward=multicast_forward,
            is_in_use=is_in_use,
            name=name,
            max_adaptive_eth_num=max_adaptive_eth_num,
            max_adaptive_pots_num=max_adaptive_pots_num,
            tagged_type=tagged_type,
            tagged_vlan_id=tagged_vlan_id,
            onu_bind_num=onu_bind_num,
        )

        service_profile_dto.additional_properties = d
        return service_profile_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
