from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.service_profile_modify_dto_mac_learning import (
    ServiceProfileModifyDTOMacLearning,
)
from ..models.service_profile_modify_dto_multicast_forward import (
    ServiceProfileModifyDTOMulticastForward,
)
from ..models.service_profile_modify_dto_multicast_mode import (
    ServiceProfileModifyDTOMulticastMode,
)
from ..models.service_profile_modify_dto_native_vlan import (
    ServiceProfileModifyDTONativeVlan,
)
from ..models.service_profile_modify_dto_tagged_type import (
    ServiceProfileModifyDTOTaggedType,
)
from ..types import UNSET, Unset

T = TypeVar("T", bound="ServiceProfileModifyDTO")


@_attrs_define
class ServiceProfileModifyDTO:
    """
    Attributes:
        service_id (int): Service profile ID should be within the range of 1 to 512
        multicast_forward (ServiceProfileModifyDTOMulticastForward): Set the multicast packet forwarding mode of the
            ONT. NativeVlan should be a value as follows:UNCONCERN,TAGGED,UNTAGGED
        name (str | Unset): Name of the service profile. No user configuration is automatically generated by the device.
            The name should contain 1 to 32 characters, including upper and lower letters, numbers, and symbols (-@_:/.).
        eth_num (int | Unset): Number of eth port.EthNum should be within the range of -1 to 24.-1 indicates that the
            number of ports is adaptive. The default value is -1.
        max_adaptive_eth_num (int | Unset): Set the maximum number of automatically recognized ETH ports.When ethNum is
            set to -1, a prompt will appear.MaxAdaptiveEthNum should be within the range of 0 to 24
        pots_num (int | Unset): Number of ONU pots.PotsNum should be within the range of -1 to 8.-1 indicates that the
            number of ports is adaptive. The default value is -1.
        max_adaptive_pots_num (int | Unset): Set the maximum number of automatically recognized potsWhen potsNum is set
            to -1, a prompt will appear.MaxAdaptivePotsNum should be within the range of 0 to 4
        mac_learning (ServiceProfileModifyDTOMacLearning | Unset): Enable/disable ONT MAC address learning function.
            MacLearning should be a value as follows:DISABLE,ENABLE
        multicast_mode (ServiceProfileModifyDTOMulticastMode | Unset): Set the multicast mode of the ONT. MulticastMode
            should be a value as follows:UNCONCERN,IGMP_SNOOPING,OLT_CONTROL
        tagged_type (ServiceProfileModifyDTOTaggedType | Unset): TaggedType should be a value as
            follows:TRANSPARENT,TRANSLATION
        tagged_vlan_id (int | Unset): TaggedVlanId should be within the range of 1–4094
        native_vlan (ServiceProfileModifyDTONativeVlan | Unset): The ONT's concern for Native VLAN .NativeVlan should be
            a value as follows:UNCONCERN,CONCERN
    """

    service_id: int
    multicast_forward: ServiceProfileModifyDTOMulticastForward
    name: str | Unset = UNSET
    eth_num: int | Unset = UNSET
    max_adaptive_eth_num: int | Unset = UNSET
    pots_num: int | Unset = UNSET
    max_adaptive_pots_num: int | Unset = UNSET
    mac_learning: ServiceProfileModifyDTOMacLearning | Unset = UNSET
    multicast_mode: ServiceProfileModifyDTOMulticastMode | Unset = UNSET
    tagged_type: ServiceProfileModifyDTOTaggedType | Unset = UNSET
    tagged_vlan_id: int | Unset = UNSET
    native_vlan: ServiceProfileModifyDTONativeVlan | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        service_id = self.service_id

        multicast_forward = self.multicast_forward.value

        name = self.name

        eth_num = self.eth_num

        max_adaptive_eth_num = self.max_adaptive_eth_num

        pots_num = self.pots_num

        max_adaptive_pots_num = self.max_adaptive_pots_num

        mac_learning: str | Unset = UNSET
        if not isinstance(self.mac_learning, Unset):
            mac_learning = self.mac_learning.value

        multicast_mode: str | Unset = UNSET
        if not isinstance(self.multicast_mode, Unset):
            multicast_mode = self.multicast_mode.value

        tagged_type: str | Unset = UNSET
        if not isinstance(self.tagged_type, Unset):
            tagged_type = self.tagged_type.value

        tagged_vlan_id = self.tagged_vlan_id

        native_vlan: str | Unset = UNSET
        if not isinstance(self.native_vlan, Unset):
            native_vlan = self.native_vlan.value

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "serviceId": service_id,
                "multicastForward": multicast_forward,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if eth_num is not UNSET:
            field_dict["ethNum"] = eth_num
        if max_adaptive_eth_num is not UNSET:
            field_dict["maxAdaptiveEthNum"] = max_adaptive_eth_num
        if pots_num is not UNSET:
            field_dict["potsNum"] = pots_num
        if max_adaptive_pots_num is not UNSET:
            field_dict["maxAdaptivePotsNum"] = max_adaptive_pots_num
        if mac_learning is not UNSET:
            field_dict["macLearning"] = mac_learning
        if multicast_mode is not UNSET:
            field_dict["multicastMode"] = multicast_mode
        if tagged_type is not UNSET:
            field_dict["taggedType"] = tagged_type
        if tagged_vlan_id is not UNSET:
            field_dict["taggedVlanId"] = tagged_vlan_id
        if native_vlan is not UNSET:
            field_dict["nativeVlan"] = native_vlan

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        service_id = d.pop("serviceId")

        multicast_forward = ServiceProfileModifyDTOMulticastForward(
            d.pop("multicastForward")
        )

        name = d.pop("name", UNSET)

        eth_num = d.pop("ethNum", UNSET)

        max_adaptive_eth_num = d.pop("maxAdaptiveEthNum", UNSET)

        pots_num = d.pop("potsNum", UNSET)

        max_adaptive_pots_num = d.pop("maxAdaptivePotsNum", UNSET)

        _mac_learning = d.pop("macLearning", UNSET)
        mac_learning: ServiceProfileModifyDTOMacLearning | Unset
        if isinstance(_mac_learning, Unset):
            mac_learning = UNSET
        else:
            mac_learning = ServiceProfileModifyDTOMacLearning(_mac_learning)

        _multicast_mode = d.pop("multicastMode", UNSET)
        multicast_mode: ServiceProfileModifyDTOMulticastMode | Unset
        if isinstance(_multicast_mode, Unset):
            multicast_mode = UNSET
        else:
            multicast_mode = ServiceProfileModifyDTOMulticastMode(_multicast_mode)

        _tagged_type = d.pop("taggedType", UNSET)
        tagged_type: ServiceProfileModifyDTOTaggedType | Unset
        if isinstance(_tagged_type, Unset):
            tagged_type = UNSET
        else:
            tagged_type = ServiceProfileModifyDTOTaggedType(_tagged_type)

        tagged_vlan_id = d.pop("taggedVlanId", UNSET)

        _native_vlan = d.pop("nativeVlan", UNSET)
        native_vlan: ServiceProfileModifyDTONativeVlan | Unset
        if isinstance(_native_vlan, Unset):
            native_vlan = UNSET
        else:
            native_vlan = ServiceProfileModifyDTONativeVlan(_native_vlan)

        service_profile_modify_dto = cls(
            service_id=service_id,
            multicast_forward=multicast_forward,
            name=name,
            eth_num=eth_num,
            max_adaptive_eth_num=max_adaptive_eth_num,
            pots_num=pots_num,
            max_adaptive_pots_num=max_adaptive_pots_num,
            mac_learning=mac_learning,
            multicast_mode=multicast_mode,
            tagged_type=tagged_type,
            tagged_vlan_id=tagged_vlan_id,
            native_vlan=native_vlan,
        )

        service_profile_modify_dto.additional_properties = d
        return service_profile_modify_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
