from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from ..models.traffic_profile_vo_inner_priority import TrafficProfileVOInnerPriority
from ..models.traffic_profile_vo_priority import TrafficProfileVOPriority
from ..models.traffic_profile_vo_priority_policy import TrafficProfileVOPriorityPolicy
from ..models.traffic_profile_vo_rate_limit_status import (
    TrafficProfileVORateLimitStatus,
)
from ..types import UNSET, Unset

T = TypeVar("T", bound="TrafficProfileVO")


@_attrs_define
class TrafficProfileVO:
    """Content

    Attributes:
        rate_limit_status (TrafficProfileVORateLimitStatus): Whether to enable rate limit.RateLimitStatus should be a
            value as follows:DISABLE,ENABLE.ENABLE by default.When enabled, CIR must be configured, while CBS, PIR, and PBS
            parameters are optional.When disabled, the CIR, CBS, PIR, and PBS parameters are grayed out and cannot be
            configured.
        priority (TrafficProfileVOPriority): Priority type of the traffic profile.Priority should be a value as
            follows:ASSIGNED,USER_COS
        priority_value (int): Priority value of the traffic profile.PriorityValue should be within the range of 0 to 7
        inner_priority (TrafficProfileVOInnerPriority): Inner priority type of the traffic profile,innerPriority should
            be a value as follows ASSIGNED, NONE, USER_COS, USER_INNER_COS
        priority_policy (TrafficProfileVOPriorityPolicy): Traffic priority policy should be a value as
            follows:LOCAL_SETTING, TAG_IN_PACKAGE, TAG_IN_INGRESS_PACKAGE
        name (str | Unset): Name of the traffic profile. No user configuration is automatically generated by the device.
            The name should contain 1 to 32 characters, including upper and lower letters, numbers, and symbols (-@_:/.).
        cir_value (int | Unset): CirValue should be within the range of 128 to 10240000
        cbs_value (int | Unset): CbsValue should be within the range of 2000 to 10240000
        pir_value (int | Unset): PirValue should be within the range of 128 to 10240000
        pbs_value (int | Unset): PbsValue should be within the range of 2000 to 10240000
        inner_priority_value (int | Unset): Inner priority value of the traffic profile.InnerPriorityValue should be
            within the range of 0 to 7
        in_use (str | Unset): Whether the Traffic Profile is in use; if it is in use, it cannot be deleted.
        traffic_id (int | Unset): Traffic profile ID.TrafficId should be within the range of 1 to 512
    """

    rate_limit_status: TrafficProfileVORateLimitStatus
    priority: TrafficProfileVOPriority
    priority_value: int
    inner_priority: TrafficProfileVOInnerPriority
    priority_policy: TrafficProfileVOPriorityPolicy
    name: str | Unset = UNSET
    cir_value: int | Unset = UNSET
    cbs_value: int | Unset = UNSET
    pir_value: int | Unset = UNSET
    pbs_value: int | Unset = UNSET
    inner_priority_value: int | Unset = UNSET
    in_use: str | Unset = UNSET
    traffic_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        rate_limit_status = self.rate_limit_status.value

        priority = self.priority.value

        priority_value = self.priority_value

        inner_priority = self.inner_priority.value

        priority_policy = self.priority_policy.value

        name = self.name

        cir_value = self.cir_value

        cbs_value = self.cbs_value

        pir_value = self.pir_value

        pbs_value = self.pbs_value

        inner_priority_value = self.inner_priority_value

        in_use = self.in_use

        traffic_id = self.traffic_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "rateLimitStatus": rate_limit_status,
                "priority": priority,
                "priorityValue": priority_value,
                "innerPriority": inner_priority,
                "priorityPolicy": priority_policy,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if cir_value is not UNSET:
            field_dict["cirValue"] = cir_value
        if cbs_value is not UNSET:
            field_dict["cbsValue"] = cbs_value
        if pir_value is not UNSET:
            field_dict["pirValue"] = pir_value
        if pbs_value is not UNSET:
            field_dict["pbsValue"] = pbs_value
        if inner_priority_value is not UNSET:
            field_dict["innerPriorityValue"] = inner_priority_value
        if in_use is not UNSET:
            field_dict["inUse"] = in_use
        if traffic_id is not UNSET:
            field_dict["trafficId"] = traffic_id

        return field_dict

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        rate_limit_status = TrafficProfileVORateLimitStatus(d.pop("rateLimitStatus"))

        priority = TrafficProfileVOPriority(d.pop("priority"))

        priority_value = d.pop("priorityValue")

        inner_priority = TrafficProfileVOInnerPriority(d.pop("innerPriority"))

        priority_policy = TrafficProfileVOPriorityPolicy(d.pop("priorityPolicy"))

        name = d.pop("name", UNSET)

        cir_value = d.pop("cirValue", UNSET)

        cbs_value = d.pop("cbsValue", UNSET)

        pir_value = d.pop("pirValue", UNSET)

        pbs_value = d.pop("pbsValue", UNSET)

        inner_priority_value = d.pop("innerPriorityValue", UNSET)

        in_use = d.pop("inUse", UNSET)

        traffic_id = d.pop("trafficId", UNSET)

        traffic_profile_vo = cls(
            rate_limit_status=rate_limit_status,
            priority=priority,
            priority_value=priority_value,
            inner_priority=inner_priority,
            priority_policy=priority_policy,
            name=name,
            cir_value=cir_value,
            cbs_value=cbs_value,
            pir_value=pir_value,
            pbs_value=pbs_value,
            inner_priority_value=inner_priority_value,
            in_use=in_use,
            traffic_id=traffic_id,
        )

        traffic_profile_vo.additional_properties = d
        return traffic_profile_vo

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
